# Description:
# Main snakemake file that contains the rules, the output files, and 
# configures the order of rule execution.

# Author:
# Caleb Carr

# Imports
import pandas as pd 
import os
from snakemake.utils import min_version
min_version("7.25.4")

# Initialize config file global variable
configfile: "Configure/config.yml"


# Rules included from Rules/ directory 
include: "Rules/download_and_process_accessions.smk"
include: "Rules/augur_processing.smk"
include: "Rules/calculate_sequence_variation.smk"

# Output files
rule all:
    """ 
    This rule controls all the output files expected from the workflow. 
    """
    input:
        # Metadata
        config["Metadata"],
        # Fasta sequences
        config["Nucleotide_sequences"],
        # Indexed files
        config["Nucleotide_sequences_indexed"],
        # Alignment files
        config["Nucleotide_alignment"],
        # Raw tree files
        config["Nucleotide_raw_tree"],
        # Tree files
        config["Nucleotide_tree"],
        config["Nucleotide_tree_nodes"],
        config["Nucleotide_tree_traits"],
        config["Nucleotide_tree_mutations"],
        config["Nucleotide_AA_mutations"],
        # Exported Auspice file
        config["Auspice_tree"],
        # Processed alignment
        config["Glycoprotein_alignment"],
        # Natural variation
        config["Glycoprotein_variation"],

# Make DAG of rule execution
rule make_DAG:
    """
    This rule produces a DAG graph of rule execution order.
    """
    shell:
        """
        mkdir -p Results/DAG/
        snakemake --rulegraph | dot -Tpdf > Results/DAG/dag.pdf
        """
